### ISSUE TITLE
Rendering error: Cannot perform runtime binding on a null reference

### ISSUE THREAD

**Issue by reaper90202** [timofey260/RWE-Plus#43]
Console Output (after rendering)
```
Start render
DCM_HW01: Exception while rendering!
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure, CallSite, Object, String)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Drizzle.Ported.renderStart.exitframe() in /home/runner/work/Drizzle/Drizzle/Drizzle.Ported/Translated/Behavior.renderStart.cs:line 93
   at Drizzle.Logic.Rendering.LevelRenderer.RenderStart() in /home/runner/work/Drizzle/Drizzle/Drizzle.Logic/Rendering/LevelRenderer.RenderCore.cs:line 96
   at Drizzle.Logic.Rendering.LevelRenderer.DoRender() in /home/runner/work/Drizzle/Drizzle/Drizzle.Logic/Rendering/LevelRenderer.RenderCore.cs:line 25
   at Program.<>c__DisplayClass0_1.<<Main>$>b__5(String s) in /home/runner/work/Drizzle/Drizzle/Drizzle.ConsoleApp/Program.cs:line 86
Finished rendering in 00:00:05.8054725. 1 errored, 0 succeeded
```

**Comment by reaper90202** [comment]
CrashLog.txt
```
Traceback (most recent call last):
  File "widgets.py", line 160, in blit
  File "widgets.py", line 689, in onclick
  File "FE.py", line 135, in selectorset
  File "widgets.py", line 827, in setbyname
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LevelProcess.py", line 120, in mainprocessupdate
  File "LevelProcess.py", line 538, in update
  File "FE.py", line 139, in blit
  File "widgets.py", line 710, in blit
  File "widgets.py", line 162, in blit
TypeError: Selector.onclick() missing 1 required positional argument: 'button'
This is why RWE+ crashed^^^
Sorry
```

**Comment by reaper90202** [comment]
Seems to have been fixed by expanding my map by 2 in each direction. And also seems to have been a Drizzle issue, not RWE+
