### ISSUE TITLE
RWE+ crash

### ISSUE THREAD

**Issue by doubted-01** [timofey260/RWE-Plus#44]
RWE+ crashes immediately upon an attempt to open any files I've created after the first two in the Levels folder

**Comment by timofey260** [comment]
Can you send the crash log

**Comment by doubted-01** [comment]
Traceback (most recent call last):
  File "C:\Users\amend\Downloads\RWE-Plus-master\RWE-Plus-master\widgets.py", line 160, in blit
    self.onpress(self)
TypeError: LoadMenu.open() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\amend\Downloads\RWE-Plus-master\RWE-Plus-master\LevelProcess.py", line 122, in mainprocessupdate
    self.mainprocess.update()
  File "C:\Users\amend\Downloads\RWE-Plus-master\RWE-Plus-master\LevelProcess.py", line 554, in update
    self.menu.blit()
  File "C:\Users\amend\Downloads\RWE-Plus-master\RWE-Plus-master\LD.py", line 86, in blit
    super().blit()
  File "C:\Users\amend\Downloads\RWE-Plus-master\RWE-Plus-master\menuclass.py", line 438, in blit
    i.blit(fontsize)
  File "C:\Users\amend\Downloads\RWE-Plus-master\RWE-Plus-master\widgets.py", line 162, in blit
    self.onpress()
  File "C:\Users\amend\Downloads\RWE-Plus-master\RWE-Plus-master\LD.py", line 93, in open
    self.sendtoowner("open")
  File "C:\Users\amend\Downloads\RWE-Plus-master\RWE-Plus-master\menuclass.py", line 80, in sendtoowner
    self.owner.recievemessage(message)
  File "C:\Users\amend\Downloads\RWE-Plus-master\RWE-Plus-master\LevelProcess.py", line 335, in recievemessage
    self.__init__(self.manager, file)
  File "C:\Users\amend\Downloads\RWE-Plus-master\RWE-Plus-master\LevelProcess.py", line 203, in __init__
    self.launchload(file)
  File "C:\Users\amend\Downloads\RWE-Plus-master\RWE-Plus-master\LevelProcess.py", line 255, in launchload
    self.file = turntoproject(open(level, "r").read())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amend\Downloads\RWE-Plus-master\RWE-Plus-master\lingotojson.py", line 95, in turntoproject
    proj["GE"] = eval(lines[0])  # geometry
                 ^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'VR' is not defined
This is why RWE+ crashed^^^
Sorry

^there's the crash log, i also discovered it will open the .wep files, but not .txt
it's very likely a user error, i just set up RWE+ on my computer recently

**Comment by timofey260** [comment]
Are you sure you are using normal editor txt files instead of rendered txt's?

**Comment by timofey260** [comment]
Closed due to issue being stale
