### ISSUE TITLE
Why can't I render my room?

### ISSUE THREAD

**Issue by TartarugaAltamenteLubrificada** [timofey260/RWE-Plus#57]
I still think I'm doing something wrong, but I still haven't figured out why.

![image](https://github.com/timofey260/RWE-Plus/assets/88255174/aeac65dc-0796-494d-a70e-360d2f7efd1e)

Please someone help me here I just don't understand hehe

**Comment by MizzyMizi** [comment]
Could you provide more details? 

If it is not too much please show your full room geometry, maybe the issue is in plain sight.

Separate screencap of the Props Menu too, I remember a strange issue I once had.

**Comment by TartarugaAltamenteLubrificada** [comment]
I don't quite understand what you're asking me, so I'm going to send you screenshots of several things

![image](https://github.com/timofey260/RWE-Plus/assets/88255174/6389c196-24c5-4483-9faf-61c846a38ea5)
![image](https://github.com/timofey260/RWE-Plus/assets/88255174/6a296de6-a533-471f-b984-723e2c5ee06f)
![image](https://github.com/timofey260/RWE-Plus/assets/88255174/d33cc76e-8460-4704-b7b5-eab48864bead)
![image](https://github.com/timofey260/RWE-Plus/assets/88255174/3d083017-3576-4dcd-82d3-dc69bc303559)
![image](https://github.com/timofey260/RWE-Plus/assets/88255174/eb674511-2b1f-41c9-abb9-68c2e2a1bc4e)
![image](https://github.com/timofey260/RWE-Plus/assets/88255174/c2cf01cc-3d54-45c3-9e07-34feba0c476c)
![image](https://github.com/timofey260/RWE-Plus/assets/88255174/f8e18d3a-d708-4b3b-997f-05d2c9d7826e)

**Comment by TartarugaAltamenteLubrificada** [comment]
![image](https://github.com/timofey260/RWE-Plus/assets/88255174/594b6932-018f-4884-88a3-402a332f2f7a)
![image](https://github.com/timofey260/RWE-Plus/assets/88255174/13008e46-7cbf-4fd8-8d05-f1009436377c)
![image](https://github.com/timofey260/RWE-Plus/assets/88255174/c47e5a39-a5ce-465b-9b68-6192e52f8c20)
![image](https://github.com/timofey260/RWE-Plus/assets/88255174/a50b7543-c7c8-4364-99d5-a44ed22aae58)

**Comment by MizzyMizi** [comment]
hmm.... I don't know, sorry.

Maybe the problem is caused by the white border being put at the end of the level? I don't think you're suppose to put the entire border there

**Comment by timofey260** [comment]
any more info in console?

**Comment by TartarugaAltamenteLubrificada** [comment]
> Mais alguma informação no console?

File name: "'C:\Users\Pichau\Documents\RWE+_win\LevelEditorProjects\Minhocas.txt'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at Drizzle.Lingo.Runtime.Xtra.FileIOXtra.openfile(String filePath, LingoNumber mode) in C:\Users\zacha\source\repos\Drizzle\Drizzle.Lingo.Runtime\Xtra\FileIOXtra.cs:line 22
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Drizzle.Ported.loadLevel.loadlevel(Object lvlname, Object fullpath) in C:\Users\zacha\source\repos\Drizzle\Drizzle.Ported\Translated\Behavior.loadLevel.cs:line 143
   at Drizzle.Logic.EditorRuntimeHelpers.RunLoadLevel(LingoRuntime runtime, String filePath) in C:\Users\zacha\source\repos\Drizzle\Drizzle.Logic\EditorRuntimeHelpers.cs:line 24
   at Program.<>c__DisplayClass0_1.<<Main>$>b__5(String s) in C:\Users\zacha\source\repos\Drizzle\Drizzle.ConsoleApp\Program.cs:line 80
Finished rendering in 00:00:00.1579988. 2 errored, 0 succeeded"

a part of it

**Comment by TartarugaAltamenteLubrificada** [comment]
> hmm.... Não sei, desculpe.
> 
> Talvez o problema seja causado pela borda branca ser colocada no final do nível? Eu não acho que você vai colocar toda a fronteira lá

I already tested this, nothing changed

**Comment by timofey260** [comment]
> > Mais alguma informação no console?
> 
> File name: "'C:\Users\Pichau\Documents\RWE+_win\LevelEditorProjects\Minhocas.txt' at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options) at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode) at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode) at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode) at System.IO.File.Open(String path, FileMode mode, FileAccess access) at Drizzle.Lingo.Runtime.Xtra.FileIOXtra.openfile(String filePath, LingoNumber mode) in C:\Users\zacha\source\repos\Drizzle\Drizzle.Lingo.Runtime\Xtra\FileIOXtra.cs:line 22 at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2) at Drizzle.Ported.loadLevel.loadlevel(Object lvlname, Object fullpath) in C:\Users\zacha\source\repos\Drizzle\Drizzle.Ported\Translated\Behavior.loadLevel.cs:line 143 at Drizzle.Logic.EditorRuntimeHelpers.RunLoadLevel(LingoRuntime runtime, String filePath) in C:\Users\zacha\source\repos\Drizzle\Drizzle.Logic\EditorRuntimeHelpers.cs:line 24 at Program.<>c__DisplayClass0_1.<
> 
> $>b__5(String s) in C:\Users\zacha\source\repos\Drizzle\Drizzle.ConsoleApp\Program.cs:line 80
> Finished rendering in 00:00:00.1579988. 2 errored, 0 succeeded"
> a part of it

i think that console doesn't have access to the txt file, as solution you can try to open drizzle application yourself and try rendering it here
drizzle/drizzleEditor.exe
