### ISSUE TITLE
Cannon open light editor

### ISSUE THREAD

**Issue by MizzyMizi** [timofey260/RWE-Plus#60]
Opened a pre-existing level that had been resized over it's time...
![light](https://github.com/timofey260/RWE-Plus/assets/111175647/f45deff7-0c23-4b65-adea-c90886b6af95)
Opened a brand new leveland tried to open light editor:
![lightnew](https://github.com/timofey260/RWE-Plus/assets/111175647/4bd30935-85a3-4d47-8313-63b78f6d6de6)

It is important to note that my level editor projects is through a symlink, it worked fine before the update but this may be what caused the issue or it might just not work.

Also the RWE+ says that it crashed even though it still is running?

Traceback (most recent call last):
  File "widgets.py", line 160, in blit
TypeError: MN.LE() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "LevelProcess.py", line 122, in mainprocessupdate
  File "LevelProcess.py", line 554, in update
  File "MN.py", line 20, in blit
  File "menuclass.py", line 841, in blit
  File "menuclass.py", line 438, in blit
  File "widgets.py", line 162, in blit
  File "MN.py", line 36, in LE
  File "menuclass.py", line 80, in sendtoowner
  File "LevelProcess.py", line 340, in recievemessage
  File "LE.py", line 42, in __init__
TypeError: unsupported operand type(s) for +: 'WindowsPath' and 'str'
This is why RWE+ crashed^^^
Sorry

I hope this is all the needed information

Everything else still works perfectly

**Comment by ddemile** [comment]
The hotkeys menu is also broken

**Comment by MizzyMizi** [comment]
The light editor is infact fixed for me, so thank super duper very much!

**Comment by timofey260** [comment]
no problem but that's something i should've found out before making previous release
