### ISSUE TITLE
Room Not Rendering

### ISSUE THREAD

**Issue by BowLuckie** [timofey260/RWE-Plus#65]
Im not sure if this is my fault or if this is the programs fault but i just cant seem to get my room to render. it always gives me this error:

Initializing Zygote runtime
Starting render of 4 levels
Program: Exception while rendering!
Rain: Exception while rendering!
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (x86)\Steam\steamapps\common\Rain World\RainWorld_Data\StreamingAssets\mods\SolitaryGraveyard\levels\(x86)\Steam\steamapps\common\Rain.txt'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at Drizzle.Lingo.Runtime.Xtra.FileIOXtra.openfile(String filePath, LingoNumber mode) in /home/runner/work/Drizzle/Drizzle/Drizzle.Lingo.Runtime/Xtra/FileIOXtra.cs:line 22
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Drizzle.Ported.loadLevel.loadlevel(Object lvlname, Object fullpath) in /home/runner/work/Drizzle/Drizzle/Drizzle.Ported/Translated/Behavior.loadLevel.cs:line 143
   at Drizzle.Logic.EditorRuntimeHelpers.RunLoadLevel(LingoRuntime runtime, String filePath) in /home/runner/work/Drizzle/Drizzle/Drizzle.Logic/EditorRuntimeHelpers.cs:line 24
   at Program.<>c__DisplayClass0_1.<<Main>$>b__5(String s) in /home/runner/work/Drizzle/Drizzle/Drizzle.ConsoleApp/Program.cs:line 80
System.IO.FileNotFoundException: Could not find file 'C:\Program.txt'.
File name: 'C:\Program.txt'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at Drizzle.Lingo.Runtime.Xtra.FileIOXtra.openfile(String filePath, LingoNumber mode) in /home/runner/work/Drizzle/Drizzle/Drizzle.Lingo.Runtime/Xtra/FileIOXtra.cs:line 22
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Drizzle.Ported.loadLevel.loadlevel(Object lvlname, Object fullpath) in /home/runner/work/Drizzle/Drizzle/Drizzle.Ported/Translated/Behavior.loadLevel.cs:line 143
   at Drizzle.Logic.EditorRuntimeHelpers.RunLoadLevel(LingoRuntime runtime, String filePath) in /home/runner/work/Drizzle/Drizzle/Drizzle.Logic/EditorRuntimeHelpers.cs:line 24
   at Program.<>c__DisplayClass0_1.<<Main>$>b__5(String s) in /home/runner/work/Drizzle/Drizzle/Drizzle.ConsoleApp/Program.cs:line 80
SG_A01: Exception while rendering!
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (x86)\Steam\steamapps\common\Rain World\RainWorld_Data\StreamingAssets\mods\SolitaryGraveyard\levels\World\RainWorld_Data\StreamingAssets\mods\SolitaryGraveyard\levels\SG_A01.txt'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at Drizzle.Lingo.Runtime.Xtra.FileIOXtra.openfile(String filePath, LingoNumber mode) in /home/runner/work/Drizzle/Drizzle/Drizzle.Lingo.Runtime/Xtra/FileIOXtra.cs:line 22
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Drizzle.Ported.loadLevel.loadlevel(Object lvlname, Object fullpath) in /home/runner/work/Drizzle/Drizzle/Drizzle.Ported/Translated/Behavior.loadLevel.cs:line 143
   at Drizzle.Logic.EditorRuntimeHelpers.RunLoadLevel(LingoRuntime runtime, String filePath) in /home/runner/work/Drizzle/Drizzle/Drizzle.Logic/EditorRuntimeHelpers.cs:line 24
   at Program.<>c__DisplayClass0_1.<<Main>$>b__5(String s) in /home/runner/work/Drizzle/Drizzle/Drizzle.ConsoleApp/Program.cs:line 80
Files: Exception while rendering!
System.IO.FileNotFoundException: Could not find file 'C:\Program Files (x86)\Steam\steamapps\common\Rain World\RainWorld_Data\StreamingAssets\mods\SolitaryGraveyard\levels\Files.txt'.
File name: 'C:\Program Files (x86)\Steam\steamapps\common\Rain World\RainWorld_Data\StreamingAssets\mods\SolitaryGraveyard\levels\Files.txt'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at Drizzle.Lingo.Runtime.Xtra.FileIOXtra.openfile(String filePath, LingoNumber mode) in /home/runner/work/Drizzle/Drizzle/Drizzle.Lingo.Runtime/Xtra/FileIOXtra.cs:line 22
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Drizzle.Ported.loadLevel.loadlevel(Object lvlname, Object fullpath) in /home/runner/work/Drizzle/Drizzle/Drizzle.Ported/Translated/Behavior.loadLevel.cs:line 143
   at Drizzle.Logic.EditorRuntimeHelpers.RunLoadLevel(LingoRuntime runtime, String filePath) in /home/runner/work/Drizzle/Drizzle/Drizzle.Logic/EditorRuntimeHelpers.cs:line 24
   at Program.<>c__DisplayClass0_1.<<Main>$>b__5(String s) in /home/runner/work/Drizzle/Drizzle/Drizzle.ConsoleApp/Program.cs:line 80
Finished rendering in 00:00:00.0912589. 4 errored, 0 succeeded

I could be doing something wrong but i dont know how to fix it

**Comment by timofey260** [comment]
it's either because pathing issue(which got fixed with latest release) or you are opening the wrong type of txt files
