### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by N-5278** [timofey260/RWE-Plus#75]
After starting a render it immediately crashes with this error:

Initializing Zygote runtime
Unhandled exception. Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure, CallSite, Object)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Drizzle.Ported.startUp.exitframe() in C:\Users\zacha\source\repos\Drizzle\Drizzle.Ported\Translated\Behavior.startUp.cs:line 298
   at Drizzle.Logic.EditorRuntimeHelpers.RunStartup(LingoRuntime runtime) in C:\Users\zacha\source\repos\Drizzle\Drizzle.Logic\EditorRuntimeHelpers.cs:line 11
   at Program.<<Main>$>g__MakeZygoteRuntime|0_3() in C:\Users\zacha\source\repos\Drizzle\Drizzle.ConsoleApp\Program.cs:line 168
   at Program.<>c__DisplayClass0_0.<<Main>$>g__DoCmdRender|0(VerbRender options) in C:\Users\zacha\source\repos\Drizzle\Drizzle.ConsoleApp\Program.cs:line 46
   at Program.<Main>$(String[] args) in C:\Users\zacha\source\repos\Drizzle\Drizzle.ConsoleApp\Program.cs:line 36

Up to this point, I have been messing around a lot with custom materials and props, but I did not go beyond these folders

**Comment by timofey260** [comment]
You should contact slime, creator of drizzle about this problem
